version: '3'

services:
    rcrs_server:
        image: ./rcrs_server/
        volumes:
            - ./MAP/:/map/:Z
            - ./logs/server/:/logs/
        env-file: 
            - rcrs.env

    web_viewer:
        depends_on: rcrs_server
        image: roborescue:rcrs-web-viewer
        env-file: 
            - rcrs.env     

    agent:
        depends_on: rcrs_server
        image: ./java-agent/
        volumes:
            - ./agent-code/:/agent/:Z
            - ./logs/agent/:/logs/ 
        env-file: 
            - rcrs.env

            